
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Use environment variables for Supabase URL and key
// These should be defined in a .env file in the project root
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://nuwavuuzzfvwhwmacpzh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im51d2F2dXV6emZ2d2h3bWFjcHpoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3NjA5MDQsImV4cCI6MjA2MjMzNjkwNH0.mhNKxY0E52AgoKb4ou-GCCGxXJVbkYR-eVY5Fw5SQH0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storage: localStorage,
    detectSessionInUrl: false  // Disable automatic session detection from URL
  }
});
